package exceptionpractice;

/**
 * = Exception =
 * 
 *  - An exception signals an unusual event during execution.
 *  - Exception are objects that store information and are transmitted outside the normal return sequence.
 *  - Exception are propagated back through the calling sequence until some routine catch the exception.
 *  - the information stored in the exception object can be extracted to provide error handling.
 * 
 *  
 * - throwing an exception :
 *    
 *  - The process of create Exception object.
 *  
 * - handle the exception :
 * 
 *  - The code that detects and deals with the exception.
 *  
 * - thrown :
 *    
 *  - Java code can handle an exception.
 *  
 *  
 *  = try-catch =
 *  
 *  - Code that might result in the propagation of an exception is enclosed in a try block.
 *  - This part of the code is jumped to only if an exception is raised.
 *  - when the exception is raised, the try block is considered terminated.
 *  - each catch block is attempted in order until a matching handler is found.
 *  
 *  - A try block encloses code that might generate an exception.
 *  - A catch block processed an exception.
 *  
 *   For example:
 *   
 *   - NumberFormatException :
 *    
 *    - A NumberFormatException is generated by parseInt if oneLine is not convertible to an int.
 *    - The code in the catch block is executed if the appropriate exception is matched.
 *    - then the catch block and the try/catch sequence is considered terminated.
 *    - The exception object e can give more detailed error message. 
 *    
 *  = Integer.parseInt() =
 *  
 *  - Parameter : a String containing the int representation to be parsed.
 *  - Returns : the integer value represented by the argument in decimal.
 *  - Throws : NumberFormatException - if the string does not contain a parsable integer
 */

import java.util.Scanner;

public class DivideByTwo {

	public static void main(String[] args) {

		Scanner input = new Scanner(System.in);		
		int x;		
		System.out.println("Enter an integer : ");
		
		try {
			String oneLine = input.nextLine();
			x = Integer.parseInt(oneLine); // paeseInt : parses the string argument as a decimal integer.
			System.out.println("Half of x is " + (x / 2));

		} catch (NumberFormatException e) {
			System.out.println(e);
		}

	}

}
